const qoutes= [
    'Woke up thinking about you this morning. I love you with my whole heart.',
    'Good morning, love! Wishing you a wonderful start to your day.',
    'Good morning, sunshine. I hope your day starts out wonderfully.',
    'Starting my day loving you.',
    'Good morning to the love of my life.',
    'Good morning sweetheart! Thank you for brightening all my days.',
    'You may never fully comprehend how amazing you are, but I won’t let a day go by without trying to show you.',
    'Any day is a perfect day if you’re in it.',
    'All things are transitory, but everything you are is eternal to me. I hope you start today knowing how special and loved you are.',
    'Good morning to the most luminous soul I’ve ever known! I hope your day is as wonderful as my life has been since you came into it.',
    'Good morning sleepy head! I hope you have the best day.',
    'Good morning. At some point today, call your parents and thank them for raising the most beautiful soul I’ve ever encountered.',
    'Just a morning reminder that you are the most gorgeous person I’ve ever known and that isn’t even the best thing about you.',
    'I learned how to be patient because you were worth waiting for. I hope you have the best morning.',
    'Wishing you a peaceful morning and a fulfilling day.',
    'Good morning! I hope your day is full of beautiful surprises.',
    'Good morning cutie! I would never play hide and seek with you because someone like you is impossible to find.',
    'I woke up today wondering if you are a magician because every time I look into your eyes everyone else disappears.',
    'I hope you start your day feeling as awesome as I think you are.',
    'Good morning! Just want to let you know how grateful for you I am.',
    'Good morning to the coolest person I’ve ever met!',
    'Just a morning reminder that you make the world a better place.',
    'I hope you have an awesome morning and move through your day knowing just how loved you are.',
    'Wishing the best morning to my best friend!',
    'Good morning. Thank you for being the rainbow to my storm cloud.',
    'Woke up wondering how I got lucky enough to have a friend as wonderful as you.',
    'Good morning! You’re the best and I love you. That’s all.',
    'Good morning! Just want to make sure you know that, even on days when you feel the worst, you never fail to amaze me.',
    'Good morning! Just a daily reminder to never doubt what you are capable of because I’ve seen your strength.',
    'Good morning to the most capable and courageous human I could possibly imagine.',
    'I hope you start your day knowing how much beauty you bring to the world.',
    'Repeat after me: I feel good, I smell good, I think big, and everything has the potential to be really awesome.',
    'I am inspired by you this morning and every morning to be a better person. Thank you for that.',
    'Good morning! You are the architect of your life and your talent is endless.',
    'Good morning! You got this!',
    'Rise and Shine! It’s time to show the world what you’re made of.',
    'Good morning! You are a force of nature. I hope you know that.',
    'Whatever today brings you, I know you can handle it.',
    'Wishing you a morning as awesome as you are.',
    'Good morning sunshine! I know you have a difficult day ahead, but I’m with you all the way.',
    'Good morning! You’re a Rockstar and you can do anything.',
    'Good morning to the most incredible person I know.',
    'You’ve been through so much and you’ve always come out of it stronger and wiser. I hope you remember that today.',
    'If you ever encounter a version of yourself from a parallel universe, give them a high five because they’re probably really cool too. I hope you have an awesome morning.',
    'Good morning! You are proof that amazing things can happen.',
    'I hope you start your day knowing how special you are. The beauty of your spirit is unmatched.',
    'Good morning! Just wanted to remind you are capable of greatness.  ',
    'I hope you start your day knowing that you are powerful and radiant and the universe is lucky to have you in it.',
    'Good morning sunshine. I just wanted to let you know that I might fail a million times, but as long as you’re in my life, I’ve succeeded where it matters most.',
    'Good morning! I hope you’re ready for everyone to fall in love with you again today.',
    'Watching the sunrise in the morning is spectacular, but it’s nothing compared to your smile.',
    'Good morning! Quick question for you: are you the sun? Because you bring light to everything in your orbit.',
    'This morning I realized that if you were a fictional character I wrote about in a creative writing class, the professor would say you were unrealistically wonderful.',
    'Good morning! Just letting you know that you make everything better.',
    'You’re made of stardust, and it shows. I hope you have the best morning.',
    'Good morning! It might be Monday, but you make every day feel like Saturday.',
    'Monday mornings are tough, but you are tougher.',
    'Good morning! I know you are going to make this week awesome because you always do.',
    'Mondays are always brighter when you’re with me.',
    'It’s okay if you don’t feel great on Mondays because I know for a fact that you are great every day.',
    'I promise to never complain about a Monday morning so long as you’re by my side.',
    'However you choose to start your Monday, I hope you do it with a full heart and a deep understanding of just how special you are.',
    'Good morning! Don’t forget, “What you do today can improve all your tomorrows.” —Ralph Marston',
    'Good morning! I wanted to send you this poem by Christian D. Larson for you to reflect on as you start your day'
  ]

module.exports={qoutes}